name = "handshake-union"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "handshakeunion.nexus/*"
custom_domain = true
