name = "black-butterfly-6e21"
compatibility_date = "2026-02-18"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "handshakeunion.nexus"
custom_domain = true